[features]
seeds = false
skip-lint = false
[programs.localnet]
cordelia_program = "2h4ZQdRQESZETBWh6mC9pgLGca8ytMR5GcCqMsUACyyY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "F:\\main.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
